version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest   # Replace with your image name if needed
    container_name: eureka
    build:
      context: .
      dockerfile: Dockerfile      # Assumes your Dockerfile is in the current directory
    ports:
      - "8761:8761"
    networks:
      - services-network

networks:
  services-network:
    name: "services-network"
    driver: bridge