server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          #lower-case-service-id: true
      routes:
        - id: cliente-service-clientes
          uri: lb://cliente-service
          predicates:
            - Path=/api/clientes/**
        - id: cliente-service-obras
          uri: lb://cliente-service
          predicates:
            - Path=/api/obras/**
        - id: test
          uri: https://example.com/
          predicates:
            - Path=/test/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    root: info
    springframework:
      cloud:
        gateway: trace
        