services:
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672' #Se mapea el pureto 5672 en el contenedor docker.
    networks:
      - services-network

