version: '3.8'

services:
  gateway-server:
    image: gateway-server:latest
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    enviroment:
      SPRING_EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - services-network

networks:
  services-network:
    external: true